map $request_method $skip_cache_by_method {
    default 1;
    GET     0;
}

map "$skip_cache_by_method:$http_cache_control" $no_cache {
    default      0;
    "0:no-cache" 1;
    "0:no-store" 1;
    ~^1          1;
}
